**Lecture 1**

Compute Dow Jones Index using data from Yahoo Finance .

In [ ]:
# Connecting the Python Code with the google drive
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
# Installing yfinance package
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.10/dist-packages (0.2.49)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.10/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (5.3.0)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.3.6)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2024.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.10/dist-packages (from yfinance) (3.17.8)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.6)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.0->yfinance) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (2024.8.30)

In [ ]:
# Importing necessary libraries
import numpy as np
import pandas as pd
import yfinance as yf
import datetime
from datetime import date
from datetime import timedelta

Import  the list of stocks in the Dow Jones Index

In [ ]:


DowJonesStocks = pd.read_excel('/content/drive/MyDrive/MAF data/Dow_20241117.xlsx') # reading excel file containing the constituent stocks in the Dow Index

print("******************************************")
print("Constituent Stocks of Dow Jones Index" )
DowJonesStocks

******************************************
Constituent Stocks of Dow Jones Index

   Ticker                             Name
0    AMZN                   Amazon.com Inc
1     AXP         American Express Company
2    AMGN                        Amgen Inc
3    AAPL                       Apple Inc.
4      BA             Boeing Company (The)
5     CAT                Caterpillar, Inc.
6    CSCO              Cisco Systems, Inc.
7     CVX              Chevron Corporation
8      GS  Goldman Sachs Group, Inc. (The)
9      HD           Home Depot, Inc. (The)
10    HON      Honeywell International Inc
11    IBM  International Business Machines
12    JNJ                Johnson & Johnson
13     KO          Coca-Cola Company (The)
14    JPM            JP Morgan Chase & Co.
15    MCD           McDonald's Corporation
16    MMM                       3M Company
17    MRK     Merck & Company, Inc.  (new)
18   MSFT            Microsoft Corporation
19    NKE                       Nike, Inc.
20     PG   Procter & Gamble Company (The)
21    SHW              Sherwin-Williams Co
22    TRV    The Travelers Companies, Inc.
23    UNH  UnitedHealth Group Incorporated
24    CRM                   Salesforce Inc
25   NVDA                       NVDIA corp
26     VZ      Verizon Communications Inc.
27      V                        Visa Inc.
28    WMT            Wal-Mart Stores, Inc.
29    DIS        Walt Disney Company (The)

In [ ]:
# Compiling all stock symbols in a list
stocks_list = list(DowJonesStocks.Ticker) # passing the symbols to the stocks_list , this list will be input for yfinance data call
print("************************************************************************************")
print("List of stocks whose data is going to be downloaded from Yahoo Finance Website are " )
stocks_list

************************************************************************************
List of stocks whose data is going to be downloaded from Yahoo Finance Website are

['AMZN',
 'AXP',
 'AMGN',
 'AAPL',
 'BA',
 'CAT',
 'CSCO',
 'CVX',
 'GS',
 'HD',
 'HON',
 'IBM',
 'JNJ',
 'KO',
 'JPM',
 'MCD',
 'MMM',
 'MRK',
 'MSFT',
 'NKE',
 'PG',
 'SHW',
 'TRV',
 'UNH',
 'CRM',
 'NVDA',
 'VZ',
 'V',
 'WMT',
 'DIS']

In [ ]:
# Importing data from yahoo finance server
d = datetime.timedelta(days = 5)                                               #get data for the last 10 days
data = yf.download(stocks_list, start=date.today()- d, end=date.today()) ##getting prices data using yfinance library
print("Dataset imported using yfinance library" )
print("******************************************")
data["Close"]

[*********************100%***********************]  30 of 30 completed

Dataset imported using yfinance library
******************************************

Ticker,AAPL,AMGN,AMZN,AXP,BA,CAT,CRM,CSCO,CVX,DIS,...,MSFT,NKE,NVDA,PG,SHW,TRV,UNH,V,VZ,WMT
Date,,,,,,,,,,,,,,,,,,,,,
2024-11-13 00:00:00+00:00,225.119995,301.440002,214.100006,287.640015,139.970001,387.070007,341.720001,59.180000,158.720001,102.720001,...,425.200012,76.519997,146.270004,166.580002,387.290009,256.670013,605.869995,309.480011,41.139999,85.500000
2024-11-14 00:00:00+00:00,228.220001,295.929993,211.479996,288.299988,138.139999,387.359985,331.649994,57.919998,161.800003,109.120003,...,426.890015,75.680000,146.759995,167.080002,388.459991,256.519989,593.150024,308.250000,40.869999,84.470001
2024-11-15 00:00:00+00:00,225.000000,283.609985,202.610001,286.869995,140.190002,384.070007,325.260010,57.459999,161.419998,115.080002,...,415.000000,76.660004,141.979996,169.539993,378.989990,260.820007,592.229980,309.640015,41.650002,84.250000

In [ ]:
print("******************************************")
print("Most Recent Close Price Dataset of all stocks" )
print("******************************************")
Price = data['Close'].iloc[-1] #extracting last available Close Price for each stock
Price

******************************************
Most Recent Close Price Dataset of all stocks
******************************************

Ticker
AAPL    225.000000
AMGN    283.609985
AMZN    202.610001
AXP     286.869995
BA      140.190002
CAT     384.070007
CRM     325.260010
CSCO     57.459999
CVX     161.419998
DIS     115.080002
GS      593.539978
HD      408.179993
HON     228.990005
IBM     204.990005
JNJ     154.000000
JPM     245.309998
KO       61.740002
MCD     292.630005
MMM     129.789993
MRK      96.309998
MSFT    415.000000
NKE      76.660004
NVDA    141.979996
PG      169.539993
SHW     378.989990
TRV     260.820007
UNH     592.229980
V       309.640015
VZ       41.650002
WMT      84.250000
Name: 2024-11-15 00:00:00+00:00, dtype: float64

In [ ]:
# Dow Jones Industrial Average (Dow Jones ndex) Calculation
dowDivisor = 0.16268413 #Most recent divisor for Dow Jones
dowIndex = Price.sum()/dowDivisor # Formula for calculating Dow Jones Index
print("************************************************************")
print("Most Recent value of the Dow Index : " + str(dowIndex) )
print("************************************************************")

************************************************************
Most Recent value of the Dow Index : 43444.98730900376
************************************************************

In [ ]:
# Weight Calculation of each stock in the Dow Jones Index
weights = Price/Price.sum() # Weight of each stock in the Index

print("*************************************************")
print("Weights of the stocks in the Index Portfolio : " )
print("*************************************************")
weights

*************************************************
Weights of the stocks in the Index Portfolio :
*************************************************

Ticker
AAPL    0.031834
AMGN    0.040127
AMZN    0.028667
AXP     0.040588
BA      0.019835
CAT     0.054341
CRM     0.046020
CSCO    0.008130
CVX     0.022839
DIS     0.016282
GS      0.083978
HD      0.057752
HON     0.032399
IBM     0.029003
JNJ     0.021789
JPM     0.034708
KO      0.008735
MCD     0.041403
MMM     0.018364
MRK     0.013627
MSFT    0.058717
NKE     0.010846
NVDA    0.020088
PG      0.023988
SHW     0.053622
TRV     0.036903
UNH     0.083793
V       0.043810
VZ      0.005893
WMT     0.011920
Name: 2024-11-15 00:00:00+00:00, dtype: float64

Suppose the dollar value of the portfolio equals today's DOW index. What is the portfolio weight for each component stock?

In [ ]:
# Portfolio Value = most recent dowindex
#  Dollar Value of each stock in the index
dollar_value = weights*dowIndex
print("******************************************************")
print("Dollar Value of the stocks in the Index : " )
print("******************************************************")
dollar_value

******************************************************
Dollar Value of the stocks in the Index :
******************************************************

Ticker
AAPL    1383.048242
AMGN    1743.316852
AMZN    1245.419578
AXP     1763.355744
BA       861.731273
CAT     2360.832660
CRM     1999.334599
CSCO     353.199781
CVX      992.229532
DIS      707.383085
GS      3648.419659
HD      2509.033872
HON     1407.574331
IBM     1260.049185
JNJ      946.619686
JPM     1507.891382
KO       379.508448
MCD     1798.761839
MMM      797.803654
MRK      592.006101
MSFT    2550.955646
NKE      471.219926
NVDA     872.734149
PG      1042.142176
SHW     2329.606399
TRV     1603.229567
UNH     3640.367259
V       1903.320346
VZ       256.017606
WMT      517.874731
Name: 2024-11-15 00:00:00+00:00, dtype: float64

How many  shares of each stock will you buy to track the index?

In [ ]:
# Number of shares of stocks in the Index
NumberOfShares = dollar_value/Price
print("******************************************************")
print("Number of shares of stocks in the Dow Jones Index : " )
print("******************************************************")
NumberOfShares

******************************************************
Number of shares of stocks in the Dow Jones Index :
******************************************************

Ticker
AAPL    6.146881
AMGN    6.146881
AMZN    6.146881
AXP     6.146881
BA      6.146881
CAT     6.146881
CRM     6.146881
CSCO    6.146881
CVX     6.146881
DIS     6.146881
GS      6.146881
HD      6.146881
HON     6.146881
IBM     6.146881
JNJ     6.146881
JPM     6.146881
KO      6.146881
MCD     6.146881
MMM     6.146881
MRK     6.146881
MSFT    6.146881
NKE     6.146881
NVDA    6.146881
PG      6.146881
SHW     6.146881
TRV     6.146881
UNH     6.146881
V       6.146881
VZ      6.146881
WMT     6.146881
Name: 2024-11-15 00:00:00+00:00, dtype: float64

Intuitively explain why the tracking portfolio buys equal number of each stock.

Q1. What is the return on the Dow Jones index on the most recent date?
Dow_Jones yesterday on data[close].iloc[-2]

Suppose Walmart would go ex-split (2 for 1) after market-close today.
(a) What would be the ex-split price of Walmart?
(b) What would be the ex-split value of Dow?
(c) What is the new divisor?

In [ ]:
#data.index
Price_exSplit = Price.copy()
WMT_ex_splitPrice = Price_exSplit['WMT']/2
Price_exSplit['WMT'] = WMT_ex_splitPrice
#data.columns

In [ ]:
Price_exSplit

Ticker
AAPL    225.000000
AMGN    283.609985
AMZN    202.610001
AXP     286.869995
BA      140.190002
CAT     384.070007
CRM     325.260010
CSCO     57.459999
CVX     161.419998
DIS     115.080002
GS      593.539978
HD      408.179993
HON     228.990005
IBM     204.990005
JNJ     154.000000
JPM     245.309998
KO       61.740002
MCD     292.630005
MMM     129.789993
MRK      96.309998
MSFT    415.000000
NKE      76.660004
NVDA    141.979996
PG      169.539993
SHW     378.989990
TRV     260.820007
UNH     592.229980
V       309.640015
VZ       41.650002
WMT      42.125000
Name: 2024-11-15 00:00:00+00:00, dtype: float64

In [ ]:
#dowIndex_ex-split = Price.sum()/dowDivisor # Formula for calculating Dow Jones Index
Dow_exSplit = Price_exSplit.sum()/dowDivisor
print('Dow_exSplit', round(Dow_exSplit,2), 'pre-split Dow', round(dowIndex,2))

Dow_exSplit 43186.05 pre-split Dow 43444.99

In [ ]:
new_divisor = Price_exSplit.sum() / dowIndex
new_divisor

0.16171451295994002